a = int(input('Digite um número:'))
b = int(input('Digite outro número:'))
c = int(input('Digite mais um número:'))
s = (a**2)+(b**2)+(c**2)
print('A soma dos números ao quadrado é igual a: {}'.format(s))